chore: skip ember-data-codemod and qunit-dom-codemod in tests
prevent error:

```
SyntaxError: /tmp/jscodeshift2023104-2774-wm9iah.q9gz.js: Missing semicolon. (1:3)
```